### ISSUE TITLE
Problem of plugin finding SDK

### ISSUE THREAD

**Issue by rjusher** [consulo/consulo-dotnet-core#4]
### Then dotnet-core plugin in consulo is not able to detect my .net core sdk.

![Project Structure](https://user-images.githubusercontent.com/3855349/63615387-759b5a00-c5a2-11e9-8abd-efdced9d128f.png)

The output of the command

```dotnet --list-sdks```

is the following

2.1.508 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]

So if I understand correctly I have the sdk installed but consulo is unable to find the location, and I couldn't find a way to give consulo the sdk location manually.

When I try to run the project:

![Run Command](https://user-images.githubusercontent.com/3855349/63615961-c5c6ec00-c5a3-11e9-90f4-62500e0bf155.png)

I get the following error:

![Fail Toast](https://user-images.githubusercontent.com/3855349/63615989-d4ad9e80-c5a3-11e9-8231-4b925b218f16.png)

**Comment by VISTALL** [comment]
Hello. Current .NET Core plugin is outdated. Last supported SDK was K runtime - and old first version.

After those versions - i paused dev for this plugin, due unstable Microsoft strategy, and limitation of my resources.

I can "revive" this plugin but need a time. 

Regards,

Valery

**Comment by VISTALL** [comment]
Close by duplicate https://github.com/consulo/consulo-dotnet-core/issues/5

Trying add initial support
